name: build

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.98.0'
          extended: true

      - name: Setup Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install Packages  
        run: |
          npm install workbox-build gulp gulp-shell --save-dev

      - name: Build
        run: |
          git config --global core.quotepath false  # https://github.com/reuixiy/hugo-theme-meme/issues/27
          gulp build

      - name: Deploy gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: deploy
          cname: axyc.me
          force_orphan: true
 
